
name: build pages

on:
  pull_request:
    paths-ignore:
      - '**/__tests__/**'

permissions:
  contents: write

jobs:
  ci-build-pages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          # 如果你文档需要 Git 子模块，取消注释下一行
          # submodules: true

      - name: install pnpm
        uses: pnpm/action-setup@v2
        with:
          run_install: true
          version: 7 # todo: 8


      - name: setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20
          cache: pnpm

      - name: install dependencies
        run: pnpm install --frozen-lockfile

      - name: build docs
        env:
          NODE_OPTIONS: --max_old_space_size=8192
        run: |-
          pnpm run docs:build
          > src/.vuepress/dist/.nojekyll
